apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-gp3
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: gp3
  resources:
    requests:
      storage: 1Gi

