# kind: # https://kubernetes.io/docs/reference/access-authn-authz/rbac/
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-client-provisioner-runner
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumes"]
  verbs: ["get", "watch", "list", "create", "delete"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "watch", "list", "create", "delete", "update"]

- apiGroups: ["storage.k8s.io"] # "" indicates the core API group
  resources: ["storageclasses"]
  verbs: ["get", "watch", "list", "create", "delete"]

- apiGroups: [""] # "" indicates the core API group
  resources: ["events"]
  verbs: ["get", "watch", "list", "update", "patch"]


