## DevOps Academy NGINX app 2 (EFS multi-attach)
## - Mounts the SAME PVC `efs-pvc` as app 1
## - Uses subPath `app2/` so content is isolated
## - Distinct color theme for visual differentiation

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-academy-nginx-2
  namespace: staging
  labels:
    app: devops-academy-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-academy-2
  template:
    metadata:
      labels:
        app: devops-academy-2
    spec:
      securityContext:
        fsGroup: 101                   # nginx (alpine) group id
        fsGroupChangePolicy: "OnRootMismatch"
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: efs-pvc         # <- same PVC as app 1
      initContainers:
        - name: create-app2-dir
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              mkdir -p /setup/app2/assets
              # Be permissive on EFS so nginx (gid 101) is fine
              chmod -R 0775 /setup/app2
          volumeMounts:
            - name: web-content
              mountPath: /setup
        - name: bootstrap-content-app2
          image: busybox:1.36
          command: ["/bin/sh","-c"]
          args:
            - |
              set -eu
              TARGET="/work"
              mkdir -p "$TARGET/assets"
              if [ -f "$TARGET/.bootstrapped" ]; then
                echo "App2 content already present."
                exit 0
              fi
              cat > "$TARGET/index.html" <<'HTML'
              <!DOCTYPE html>
              <html lang="en">
              <head>
                <meta charset="utf-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <title>DevOps Academy — App 2</title>
                <link rel="preconnect" href="https://fonts.googleapis.com">
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
                <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;500;700&display=swap" rel="stylesheet">
                <link rel="stylesheet" href="assets/style.css" />
              </head>
              <body>
                <div class="hero">
                  <div class="glow"></div>
                  <header>
                    <h1><span class="accent">DevOps</span> Academy — App 2</h1>
                    <p>EFS multi-attach demo (shared PVC, isolated subPath).</p>
                  </header>
                  <main>
                    <a class="btn" href="https://kubernetes.io/docs/concepts/storage/persistent-volumes/">Kubernetes Storage</a>
                    <a class="btn ghost" href="#">App 2 Rocks</a>
                  </main>
                  <footer>
                    <small>Served from PersistentVolumeClaim: efs-pvc (subPath: app2)</small>
                  </footer>
                </div>
              </body>
              </html>
              HTML
              cat > "$TARGET/assets/style.css" <<'CSS'
              :root{
                --bg:#0a0d1a; --fg:#f5f6fa; --muted:#9aa3b2; --accent:#ff8a00; --accent2:#ff3d3d;
              }
              *{box-sizing:border-box}
              html,body{height:100%;margin:0;font-family:'Inter',system-ui,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:var(--fg);background:radial-gradient(1200px 700px at 20% 10%, rgba(255,138,0,.18), transparent 60%), radial-gradient(900px 600px at 90% 90%, rgba(255,61,61,.18), transparent 60%), var(--bg);}
              .hero{min-height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:24px;text-align:center;padding:32px;position:relative;overflow:hidden}
              header h1{font-size: clamp(32px, 5vw, 64px);margin:0;letter-spacing:.5px}
              header p{margin:8px 0 0;color:var(--muted)}
              .accent{background:linear-gradient(90deg,var(--accent),var(--accent2));-webkit-background-clip:text;background-clip:text;color:transparent}
              .btn{display:inline-block;padding:12px 20px;margin:8px;border-radius:12px;font-weight:600;color:#0a0d1a;background:linear-gradient(90deg,var(--accent),var(--accent2));box-shadow:0 10px 30px rgba(255,138,0,.3);text-decoration:none;transition:transform .15s ease, filter .2s ease}
              .btn:hover{transform:translateY(-2px);filter:saturate(1.1)}
              .btn.ghost{background:transparent;color:var(--fg);border:1.5px solid rgba(255,255,255,.2)}
              footer{position:fixed;bottom:12px;left:0;right:0;text-align:center;color:var(--muted)}
              .glow{position:absolute;inset:0;pointer-events:none;background: radial-gradient(ellipse at center, rgba(255,255,255,.06) 0, rgba(255,255,255,0) 60%);}
              CSS
              printf '%s\n' "$(date -Iseconds)" > "$TARGET/.bootstrapped"
          volumeMounts:
            - name: web-content
              mountPath: /work
              subPath: app2
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: web-content
              mountPath: /usr/share/nginx/html
              subPath: app2
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: "200m"
              memory: 128Mi

---
apiVersion: v1
kind: Service
metadata:
  name: devops-academy-nginx-2
  namespace: staging
  labels:
    app: devops-academy-2
spec:
  selector:
    app: devops-academy-2
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP
